### PR TITLE
Feature/milestone2

### PR DESCRIPTION
**Pull request by gonjavi**
- Prepare the directory structure
Create a components directory in the src folder for all the presentational components.
Create a containers directory in the src folder for all the container components.
Create a actions directory with the index.js file where you'll define all the Redux actions.
Create a reducers directory with two files: books.js and index.js. The former will store the functions responsible for actions on Books, and the latter should combine all the reducers into one. For now, it will only combine the books.js reducer.
Documentation: Combine Reducers
- Implement the App component
It should only wrap BooksList and BooksForm in a div selector and display it.
Attach this component to render the function in the main index.js file.
- Implement the BooksList component
It should display the books as an html table.
Each row should contain Book ID, title and category.
It should connect to the Redux store and fetch the books from the state.
- Implement the Book component
It should accept a book object as a prop.
It should represent a single row in the Books table.
- Implement the BooksForm component
It should render a very simple form for adding books. The form should contain a book title input, a select box with categories and a submit button.
Define a constant with a collection containing the book categories: ["Action", "Biography", "History", "Horror", "Kids", "Learning", "Sci-Fi"].
- Define the Redux actions and reducers
Implement the books.js reducer with CREATE_BOOK and REMOVE_BOOK actions. Remember, your state can not be mutated!
Define the CREATE_BOOK and REMOVE_BOOK actions in actions/index.js. They should accept a book object as an argument.
- Initialize the Redux store
Create the initial state object in src/index.js. It may contain just a few books with different titles and categories.
Each book in the initial state should have a unique ID. However, we'll cheat here and implement that functionality by using the Math.random function.
Render the <App/> component wrapped in <Provider> and pass the store down to the components.

### CODE REVIEW

**Comment by gonjavi** [comment]
This is what I have done, trying to follow the requirements, how is it going? any suggestions to continue?

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
**Status: Changes Required**

Hello @gonjavi 

You are doing a great job but you need to make some changes before getting approval.

- [x] You also should create containers directory for all the container components like BooksList and BookForm should be in containers and components is only for presentational components App and Book.

- [x] You should Create the initial state object in `src/index.js`. It may contain just a few books with different titles and categories [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/InitialBooks.png)

- [x] BooksList should displays books list in html table using `Book` component

- [x] Booksform should have a state with `title` and `category`

- [x] Please fix linter errors

Submit for another review after making those changes.

Happy Coding
Adnan Afsari

**Comment by gonjavi** [comment]
OK. I have worked on the review.
however there are some stickler errors: related to bootstrap, and eslint configuration, I used the eslintrc suggested by microverse, but it is giving some errors.

Your eslint configuration output the following error:
(node:1) [ESLINT_LEGACY_ECMAFEATURES] DeprecationWarning: The 'ecmaFeatures' config file property is deprecated, and has no effect. (found in "--config » eslint-config-airbnb » /tool/node_modules/eslint-config-airbnb/rules/react.js")

I don't really know what else to do here.

**Comment by gonjavi** [comment]
BookForm route: http://localhost:3000/new

**Review by AdnanAfsari — APPROVED** [review]
**Status: Approved**

Hello @gonjavi ✋ 

Well done on making requested changes,It's a 👍  from me.

- [x] **To solve Liner Errors**-Please remove `.stickler.yml` from this repo as you already have implemented `GitHub Actions`, We do not need both configuration and it also will solve your liner errors.

Happy Coding
Adnan Afsari.

**Comment by gonjavi** [comment]
OK thanks

**Pull request merged**
